using './main.bicep'

param logAnalyticsName = 'stratrack-dev-loganalytics'
param applicationInsightsName = 'stratrack-dev-ai'
param storageAccountName = 'stratrackdevstorage'
param sqlServerName = 'stratrack-dev-sql'
param sqlDatabaseName = 'stratrack-dev-db'
param functionAppName = 'stratrack-dev-func'
param staticWebAppName = 'stratrack-dev-web'
param sqlAdminUser = 'adminuser'
param sqlAdminPassword = 'P@ssw0rd#123'
