import type { BuiltinFunction } from "./types";

export const AccountBalance: BuiltinFunction = () => 0;
export const AccountCompany: BuiltinFunction = () => "";
export const AccountCredit: BuiltinFunction = () => 0;
export const AccountCurrency: BuiltinFunction = () => "";
export const AccountEquity: BuiltinFunction = () => 0;
export const AccountFreeMargin: BuiltinFunction = () => 0;
export const AccountFreeMarginCheck: BuiltinFunction = () => 0;
export const AccountFreeMarginMode: BuiltinFunction = () => 0;
export const AccountInfoDouble: BuiltinFunction = () => 0;
export const AccountInfoInteger: BuiltinFunction = () => 0;
export const AccountInfoString: BuiltinFunction = () => "";
export const AccountLeverage: BuiltinFunction = () => 0;
export const AccountMargin: BuiltinFunction = () => 0;
export const AccountName: BuiltinFunction = () => "";
export const AccountNumber: BuiltinFunction = () => 0;
export const AccountProfit: BuiltinFunction = () => 0;
export const AccountServer: BuiltinFunction = () => "";
export const AccountStopoutLevel: BuiltinFunction = () => 0;
export const AccountStopoutMode: BuiltinFunction = () => 0;
