import type { BuiltinFunction } from "../types.js";

export const Bars: BuiltinFunction = (..._args: any[]) => 0;
export const iBars: BuiltinFunction = (..._args: any[]) => 0;
export const iBarShift: BuiltinFunction = (..._args: any[]) => -1;
export const iOpen: BuiltinFunction = (..._args: any[]) => 0;
export const iHigh: BuiltinFunction = (..._args: any[]) => 0;
export const iLow: BuiltinFunction = (..._args: any[]) => 0;
export const iClose: BuiltinFunction = (..._args: any[]) => 0;
export const iTime: BuiltinFunction = (..._args: any[]) => 0;
export const iVolume: BuiltinFunction = (..._args: any[]) => 0;
export const CopyRates: BuiltinFunction = (..._args: any[]) => 0;
export const CopyTime: BuiltinFunction = (..._args: any[]) => 0;
export const CopyOpen: BuiltinFunction = (..._args: any[]) => 0;
export const CopyHigh: BuiltinFunction = (..._args: any[]) => 0;
export const CopyLow: BuiltinFunction = (..._args: any[]) => 0;
export const CopyClose: BuiltinFunction = (..._args: any[]) => 0;
export const CopyTickVolume: BuiltinFunction = (..._args: any[]) => 0;
export const SeriesInfoInteger: BuiltinFunction = (..._args: any[]) => 0;
export const RefreshRates: BuiltinFunction = (..._args: any[]) => 0;
