name: Deploy to Azure Static Web Apps

on:
  push:
    branches:
      - main  # デプロイ対象ブランチを指定
    paths:
      - 'frontend/**'

permissions:
  id-token: write
  contents: read

env:
  VITE_API_BASE_URL: ${{ secrets.AZURE_FUNCTION_URL }}
  VITE_API_KEY: ${{ secrets.AZURE_FUNCTION_API_KEY }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: npm ci and build
        run: |
          npm ci --prefix frontend
          npm run build --prefix frontend

      - name: Deploy to Static Web App
        run: |
          npm i -g @azure/static-web-apps-cli
          swa deploy ./frontend/dist/ --env production --deployment-token ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_KIND_WATER }}
